{
 "title": "SwarmNode",
 "description": "Traefik dashboard prometheus",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   { "name": "entrypoint", "query": { "query": "label_values(entrypoint)" } }
  ]
 },
 "panels": [
  {
   "title": "Disk reads (5h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[5h])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk writes (5h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total[5h])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Seconds of IO time (5h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total[5h])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Context Switches (1h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_context_switches_total[1h])",
     "legendFormat": "fluent-bit-data"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "fluent-bit-data" }
   ]
  },
  {
   "title": "Total number of Mallocs (1h)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total[1h])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Keycloak CPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"keycloak\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "base_cpu_systemLoadAverage{job=\"keycloak\"}",
     "legendFormat": "Base CPU Load Avg"
    }
   ]
  },
  {
   "title": "forgejo: users & repos",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_users{job=\"forgejo\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "gitea_repositories{job=\"forgejo\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "$service response time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service=\"$service\"}) / sum(traefik_service_requests_total{service=\"$service\"}) * 1000"
    }
   ]
  },
  {
   "title": "Scraped metrics for job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 31 },
   "targets": [
    {
     "expr": "sum by (job)(scrape_samples_scraped)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of interrupted services (1h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    { "expr": "rate(node_intr_total[1h])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "exam-admin forgejo logins",
   "type": "stat",
   "description": "#occurences of \"exam-user\" in forgejo in the last 1h",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service_name=\"vcc_forgejo\"} |= `exam-admin` [1h])"
    }
   ]
  },
  {
   "title": "#occurences of \"admin\" in keycloak in last 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({service_name=\"vcc_auth\"} |= `admin` [24h])"
    }
   ]
  },
  {
   "title": "Status code 200 over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=\"200\"}[5m])",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Number of Dashboards",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grafana_stat_totals_dashboard", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total requests over 5min $service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\"}[5m]))",
     "legendFormat": "Total requests $service"
    }
   ]
  }
 ]
}