{
 "title": "Traefik",
 "description": "Traefik dashboard prometheus",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   { "name": "entrypoint", "query": { "query": "label_values(entrypoint)" } }
  ]
 },
 "panels": [
  {
   "title": "Traefik HTTP requests",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code, service) (rate(traefik_service_requests_total[1h]))",
     "legendFormat": "{{service}}: {{code}}"
    }
   ]
  },
  {
   "title": "Top status codes from Traefik (1h)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum by(code) (rate(traefik_service_requests_total[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg response time by Traefik in seconds (1h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_request_duration_seconds_sum[1h])) / sum(traefik_entrypoint_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traefik 200 codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=\"200\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Traefik bytes per service (1h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (rate(traefik_service_responses_bytes_total[1h]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Traefik HTTP request types (1h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(method) (rate(traefik_service_requests_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traefik logs type (1h)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({stream=\"stderr\"} |= `=debug` |= `traefik` [1h]))",
     "legendFormat": "debug logs"
    },
    {
     "expr": "sum(rate({stream=\"stderr\"} |= `=info` |= `traefik` [1h]))",
     "legendFormat": "info logs"
    },
    {
     "expr": "sum(rate({stream=\"stderr\"} |= `=warn` |= `traefik` [1h]))",
     "legendFormat": "warn logs"
    },
    {
     "expr": "sum(rate({stream=\"stderr\"} |= `=error` |= `traefik` [1h]))",
     "legendFormat": "error logs"
    }
   ]
  },
  {
   "title": "Traefik TLS requests (1h)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_tls_total[1h])",
     "legendFormat": "TLS requests"
    }
   ]
  },
  {
   "title": "Traefik errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{stream=\"stderr\"} |= `traefik` |= `error`",
     "maxLines": 20
    }
   ]
  }
 ]
}